### ISSUE TITLE
Accélerer le compactage en ne mappant que les établissements concernés

### ISSUE THREAD

**Issue by JazzyPierrot** [entrepreneur-interet-general/opensignauxfaibles#14]
Possibilité d'améliorer la performance: le map du compact prend tous les établissements, au lieu de ne prendre que les établissements concernés par une mise-à-jour des données.

**Comment by chrnin** [comment]
-> création d'un index pour identifier les occurences de siret dans value.siret
-> insertion comparative du fichier sirene pour limiter les insertions identiques
